const { v4: uuidv4 } = require('uuid');
const fs = require('fs-extra');
const path = require('path');
const os = require('os');

class ClarificationEngine {
  constructor(config, logger) {
    this.config = config;
    this.logger = logger;
    this.questionQueues = new Map();
    this.questions = new Map();
    this.responses = new Map();
    this.clarificationDir = path.join(os.homedir(), '.pix/clarification');

    this.questionTypes = [
      { id: 'yes-no', name: 'Yes/No', icon: '✅', format: 'binary', options: ['Yes', 'No'] },
      { id: 'choice', name: 'Multiple Choice', icon: '📋', format: 'select' },
      { id: 'text', name: 'Text Input', icon: '📝', format: 'text' },
      { id: 'confirm', name: 'Confirmation', icon: '⚠️', format: 'confirm', options: ['Confirm', 'Cancel'] },
      { id: 'clarify', name: 'Clarification', icon: '❓', format: 'text' },
      { id: 'priority', name: 'Priority', icon: '⬆️', format: 'select', options: ['Critical', 'High', 'Medium', 'Low'] },
      { id: 'approach', name: 'Approach Selection', icon: '🔀', format: 'select' },
      { id: 'scope', name: 'Scope Definition', icon: '🎯', format: 'text' }
    ];

    this.autoQuestionRules = [
      { trigger: 'ambiguous', questionType: 'clarify', priority: 'high', autoQueue: true },
      { trigger: 'multiple-options', questionType: 'approach', priority: 'medium', autoQueue: true },
      { trigger: 'destructive', questionType: 'confirm', priority: 'critical', autoQueue: true },
      { trigger: 'scope-change', questionType: 'scope', priority: 'medium', autoQueue: true },
      { trigger: 'unclear-intent', questionType: 'clarify', priority: 'high', autoQueue: true }
    ];
  }

  async initialize() {
    this.logger.info('Initializing Clarification Engine...');
    await fs.ensureDir(this.clarificationDir);
    await this.loadData();
    this.loadSettings();
    this.logger.info('Clarification Engine initialized');
  }

  async loadData() {
    try {
      const files = await fs.readdir(this.clarificationDir);
      for (const file of files) {
        if (file.endsWith('.json')) {
          const data = await fs.readJson(path.join(this.clarificationDir, file));
          if (data.type === 'queue') this.questionQueues.set(data.id, data);
          else if (data.type === 'question') this.questions.set(data.id, data);
        }
      }
    } catch (e) {}
  }

  loadSettings() {
    this.settings = {
      askMode: 'queue',
      queueEnabled: true,
      autoAskEnabled: true,
      pauseOnQuestion: true,
      maxQueueSize: 10,
      timeoutMs: 300000,
      defaultResponse: null,
      bypassForSafeActions: true,
      warnWhenDisabled: true,
      soundEnabled: true,
      notificationEnabled: true
    };
  }

  async createQueue(params) {
    const {
      sessionId,
      name = 'Question Queue',
      autoMode = true,
      pauseOnQuestion = true,
      timeout = 300000,
      maxQuestions = 10
    } = params;

    const id = uuidv4();
    const queue = {
      id,
      sessionId,
      name,
      autoMode,
      pauseOnQuestion,
      timeout,
      maxQuestions,
      questions: [],
      status: 'active',
      settings: {
        allowBypass: true,
        requireAllAnswers: false,
        autoResolve: false
      },
      type: 'queue',
      createdAt: new Date().toISOString()
    };

    this.questionQueues.set(id, queue);
    await this.saveQueue(queue);

    return queue;
  }

  async addQuestion(params) {
    const {
      queueId,
      content,
      type = 'clarify',
      options = [],
      context = {},
      priority = 'medium',
      required = true,
      autoGenerated = false,
      relatedGoalId = null
    } = params;

    const queue = this.questionQueues.get(queueId);
    if (!queue) throw new Error(`Queue not found: ${queueId}`);

    if (queue.questions.length >= queue.maxQuestions) {
      throw new Error('Question queue is full');
    }

    const id = uuidv4();
    const questionType = this.questionTypes.find(q => q.id === type);

    const question = {
      id,
      queueId,
      content,
      type,
      typeInfo: questionType,
      options: options.length > 0 ? options : (questionType?.options || []),
      context,
      priority,
      required,
      autoGenerated,
      relatedGoalId,
      status: 'pending',
      response: null,
      answeredAt: null,
      createdAt: new Date().toISOString()
    };

    queue.questions.push(id);
    this.questions.set(id, question);

    if (queue.pauseOnQuestion) {
      queue.status = 'waiting';
    }

    this.questionQueues.set(queueId, queue);
    await this.saveQuestion(question);
    await this.saveQueue(queue);

    return question;
  }

  async answerQuestion(questionId, answer) {
    const question = this.questions.get(questionId);
    if (!question) throw new Error(`Question not found: ${questionId}`);

    question.response = answer;
    question.status = 'answered';
    question.answeredAt = new Date().toISOString();

    const queue = this.questionQueues.get(question.queueId);
    if (queue) {
      const allAnswered = queue.questions.every(qId => {
        const q = this.questions.get(qId);
        return q && (q.status === 'answered' || !q.required);
      });

      if (allAnswered) {
        queue.status = 'active';
      }
    }

    this.questions.set(questionId, question);
    if (queue) this.questionQueues.set(queue.queueId, queue);

    await this.saveQuestion(question);
    if (queue) await this.saveQueue(queue);

    return question;
  }

  async skipQuestion(questionId) {
    return this.answerQuestion(questionId, { skipped: true, value: null });
  }

  async bypassQueue(queueId) {
    const queue = this.questionQueues.get(queueId);
    if (!queue) throw new Error(`Queue not found: ${queueId}`);

    for (const qId of queue.questions) {
      const q = this.questions.get(qId);
      if (q && q.status === 'pending') {
        q.status = 'bypassed';
        q.response = { bypassed: true };
        q.answeredAt = new Date().toISOString();
        this.questions.set(qId, q);
      }
    }

    queue.status = 'active';
    queue.bypassedAt = new Date().toISOString();
    this.questionQueues.set(queueId, queue);
    await this.saveQueue(queue);

    return queue;
  }

  async disableQueueSystem(sessionId) {
    const queue = Array.from(this.questionQueues.values()).find(q => q.sessionId === sessionId);
    if (queue) {
      queue.status = 'disabled';
      queue.disabledAt = new Date().toISOString();
      this.questionQueues.set(queue.id, queue);
      await this.saveQueue(queue);
    }

    return {
      disabled: true,
      warning: 'Question queue system has been disabled. The AI will proceed without asking questions. You can re-enable this at any time.',
      timestamp: new Date().toISOString()
    };
  }

  async enableQueueSystem(sessionId) {
    const queue = Array.from(this.questionQueues.values()).find(q => q.sessionId === sessionId);
    if (queue) {
      queue.status = 'active';
      queue.disabledAt = null;
      this.questionQueues.set(queue.id, queue);
      await this.saveQueue(queue);
    }

    return {
      enabled: true,
      message: 'Question queue system has been enabled. The AI will ask questions when needed.'
    };
  }

  async getNextQuestion(queueId) {
    const queue = this.questionQueues.get(queueId);
    if (!queue) throw new Error(`Queue not found: ${queueId}`);

    for (const qId of queue.questions) {
      const q = this.questions.get(qId);
      if (q && q.status === 'pending') {
        return q;
      }
    }

    return null;
  }

  async getQueueStatus(queueId) {
    const queue = this.questionQueues.get(queueId);
    if (!queue) throw new Error(`Queue not found: ${queueId}`);

    const questions = queue.questions.map(qId => this.questions.get(qId)).filter(Boolean);
    const pending = questions.filter(q => q.status === 'pending').length;
    const answered = questions.filter(q => q.status === 'answered').length;
    const bypassed = questions.filter(q => q.status === 'bypassed').length;

    return {
      queueId,
      status: queue.status,
      total: questions.length,
      pending,
      answered,
      bypassed,
      percentComplete: questions.length > 0 ? Math.round((answered / questions.length) * 100) : 100,
      currentQuestion: await this.getNextQuestion(queueId)
    };
  }

  async analyzeAndQueue(params) {
    const { sessionId, input, context = {} } = params;

    const queue = Array.from(this.questionQueues.values()).find(q => q.sessionId === sessionId);
    if (!queue || queue.status === 'disabled') return null;

    const issues = this.detectIssues(input, context);
    const queued = [];

    for (const issue of issues) {
      if (queue.autoMode) {
        const question = await this.addQuestion({
          queueId: queue.id,
          content: issue.question,
          type: issue.type,
          options: issue.options || [],
          context: issue.context,
          priority: issue.priority,
          autoGenerated: true
        });
        queued.push(question);
      }
    }

    return {
      issuesDetected: issues.length,
      questionsQueued: queued.length,
      questions: queued
    };
  }

  detectIssues(input, context) {
    const issues = [];
    const inputLower = input.toLowerCase();

    if (inputLower.includes('maybe') || inputLower.includes('or') || inputLower.includes('either')) {
      issues.push({
        type: 'approach',
        question: 'I see multiple options in your request. Which approach would you prefer?',
        options: this.extractOptions(input),
        priority: 'medium',
        context: { originalInput: input }
      });
    }

    if (inputLower.includes('delete') || inputLower.includes('remove') || inputLower.includes('destroy')) {
      issues.push({
        type: 'confirm',
        question: 'This action may be destructive. Are you sure you want to proceed?',
        options: ['Yes, proceed', 'No, cancel'],
        priority: 'critical',
        context: { originalInput: input }
      });
    }

    if (inputLower.includes('all') || inputLower.includes('everything') || inputLower.includes('entire')) {
      issues.push({
        type: 'scope',
        question: 'You mentioned working on everything. Should I limit the scope to specific files or directories?',
        options: ['Current directory', 'Entire project', 'Specific files'],
        priority: 'medium',
        context: { originalInput: input }
      });
    }

    if (!input.includes('.') && !input.includes('/') && input.split(' ').length < 3) {
      issues.push({
        type: 'clarify',
        question: 'Could you provide more details about what you\'d like me to do?',
        priority: 'high',
        context: { originalInput: input }
      });
    }

    return issues;
  }

  extractOptions(input) {
    const orParts = input.split(/\s+or\s+/i);
    if (orParts.length > 1) {
      return orParts.map(p => p.trim()).filter(p => p.length > 0 && p.length < 50);
    }

    const eitherParts = input.split(/\s+either\s+/i);
    if (eitherParts.length > 1) {
      return eitherParts.map(p => p.trim()).filter(p => p.length > 0 && p.length < 50);
    }

    return ['Option A', 'Option B'];
  }

  async searchForAnswer(params) {
    const { questionId, query } = params;

    return {
      questionId,
      query,
      sources: [
        { title: 'Documentation', url: 'https://docs.example.com', snippet: 'Relevant documentation...' },
        { title: 'Stack Overflow', url: 'https://stackoverflow.com', snippet: 'Community solution...' }
      ],
      suggestedAnswer: 'Based on web search, here is a suggested answer...'
    };
  }

  async getSettings() {
    return this.settings;
  }

  async updateSettings(updates) {
    this.settings = { ...this.settings, ...updates };
    return this.settings;
  }

  async getQueue(id) {
    return this.questionQueues.get(id);
  }

  listQueues(sessionId = null) {
    let queues = Array.from(this.questionQueues.values());
    if (sessionId) queues = queues.filter(q => q.sessionId === sessionId);
    return queues;
  }

  async getQuestion(id) {
    return this.questions.get(id);
  }

  listPendingQuestions(queueId) {
    const queue = this.questionQueues.get(queueId);
    if (!queue) return [];

    return queue.questions
      .map(qId => this.questions.get(qId))
      .filter(q => q && q.status === 'pending');
  }

  getQuestionTypes() {
    return this.questionTypes;
  }

  async getStats() {
    const queues = Array.from(this.questionQueues.values());
    const questions = Array.from(this.questions.values());

    return {
      queues: queues.length,
      activeQueues: queues.filter(q => q.status === 'active').length,
      disabledQueues: queues.filter(q => q.status === 'disabled').length,
      questions: questions.length,
      pendingQuestions: questions.filter(q => q.status === 'pending').length,
      answeredQuestions: questions.filter(q => q.status === 'answered').length,
      bypassedQuestions: questions.filter(q => q.status === 'bypassed').length
    };
  }

  async saveQueue(queue) {
    const filePath = path.join(this.clarificationDir, `queue-${queue.id}.json`);
    await fs.writeJson(filePath, queue, { spaces: 2 });
  }

  async saveQuestion(question) {
    const filePath = path.join(this.clarificationDir, `question-${question.id}.json`);
    await fs.writeJson(filePath, question, { spaces: 2 });
  }

  async exportClarification(format = 'json') {
    const data = {
      queues: Array.from(this.questionQueues.values()),
      questions: Array.from(this.questions.values()),
      settings: this.settings,
      stats: await this.getStats()
    };

    if (format === 'json') {
      return JSON.stringify(data, null, 2);
    }

    return data;
  }
}

module.exports = ClarificationEngine;
