const { execSync } = require('child_process');
const fs = require('fs');
const path = require('path');

class GitWorkflow {
  constructor(projectRoot) {
    this.root = projectRoot;
  }

  isRepo() {
    try { execSync('git rev-parse --is-inside-work-tree', { cwd: this.root, stdio: 'ignore' }); return true; } catch (e) { return false; }
  }

  status() {
    if (!this.isRepo()) return { error: 'Not a git repository' };
    const s = execSync('git status --porcelain', { cwd: this.root, encoding: 'utf8' });
    const branch = execSync('git branch --show-current', { cwd: this.root, encoding: 'utf8' }).trim();
    const log = execSync('git log --oneline -5', { cwd: this.root, encoding: 'utf8' }).trim();
    return { branch, files: s.split('\n').filter(Boolean), recentCommits: log.split('\n') };
  }

  autoCommit(message) {
    if (!this.isRepo()) return { error: 'Not a git repository' };
    try {
      execSync('git add -A', { cwd: this.root, stdio: 'ignore' });
      execSync(`git commit -m "${message}"`, { cwd: this.root, stdio: 'ignore' });
      return { success: true, message };
    } catch (e) { return { error: e.message }; }
  }

  createBranch(name) {
    if (!this.isRepo()) return { error: 'Not a git repository' };
    try {
      execSync(`git checkout -b ${name}`, { cwd: this.root, stdio: 'ignore' });
      return { success: true, branch: name };
    } catch (e) { return { error: e.message }; }
  }

  switchBranch(name) {
    if (!this.isRepo()) return { error: 'Not a git repository' };
    try {
      execSync(`git checkout ${name}`, { cwd: this.root, stdio: 'ignore' });
      return { success: true, branch: name };
    } catch (e) { return { error: e.message }; }
  }

  listBranches() {
    if (!this.isRepo()) return [];
    const out = execSync('git branch', { cwd: this.root, encoding: 'utf8' });
    return out.split('\n').map(b => b.replace(/^\*\s*/, '').trim()).filter(Boolean);
  }

  createPR(title, body) {
    if (!this.isRepo()) return { error: 'Not a git repository' };
    try {
      const branch = execSync('git branch --show-current', { cwd: this.root, encoding: 'utf8' }).trim();
      execSync('git push -u origin ' + branch, { cwd: this.root, stdio: 'ignore' });
      const result = execSync(`gh pr create --title "${title}" --body "${body || 'Auto-generated by Pix AI'}"`, { cwd: this.root, encoding: 'utf8' });
      return { success: true, pr: result.trim() };
    } catch (e) { return { error: e.message }; }
  }

  diff() {
    if (!this.isRepo()) return '';
    try { return execSync('git diff', { cwd: this.root, encoding: 'utf8' }); } catch (e) { return ''; }
  }

  log(count = 10) {
    if (!this.isRepo()) return [];
    try {
      const out = execSync(`git log --oneline -${count}`, { cwd: this.root, encoding: 'utf8' });
      return out.split('\n').filter(Boolean);
    } catch (e) { return []; }
  }

  stash() {
    if (!this.isRepo()) return { error: 'Not a git repository' };
    try { execSync('git stash', { cwd: this.root, stdio: 'ignore' }); return { success: true }; } catch (e) { return { error: e.message }; }
  }

  stashPop() {
    if (!this.isRepo()) return { error: 'Not a git repository' };
    try { execSync('git stash pop', { cwd: this.root, stdio: 'ignore' }); return { success: true }; } catch (e) { return { error: e.message }; }
  }
}

module.exports = GitWorkflow;
